### ISSUE TITLE
Check for SKETCHUP_CONSOLE.show

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#135] opened 2020-04-30 11:12 UTC
`SKETCHUP_CONSOLE.show` is for development, not something an extension should typically do, unless it's a development tool. 

However, developers might add this temporarily for debugging and forget to remove it before publishing.

Warn against usage of `SKETCHUP_CONSOLE.show` - if it's a false positive for the rare cases of a development tool it can be disabled for the project.

**Comment by Eneroth3** [comment] 2023-03-29 09:22
Duplicate of #84

**Closed by Eneroth3** 2023-03-29 09:22 UTC
Labels: enhancement, cop, SketchupRequirements
